# Generated by Django 4.1.5 on 2025-01-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default={'BASE_URL_ICCF': 'https://gamesarchive.iccf.com/archive', 'BASE_URL_TWIC': 'https://theweekinchess.com/zips/twic', 'FOLDER_IMPORT': 'chess_import', 'ICCF_FOLDER': 'chess/iccf', 'MAX_MISSING_TWIC': 1, 'START_TWIC_NR': 1565, 'SUB_FOLDER_UNZIPPED': 'pgn', 'SUB_FOLDER_ZST': 'zst', 'TWIC_FOLDER': 'chess/twic', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299', 'VOLUME_DOWNLOAD_ICCF': 'VOLUME_DATALAKE_DOWN', 'VOLUME_IMPORT': 'VOLUME_DATALAKE_FRITZ', 'VOLUME_TWIC': 'VOLUME_DATALAKE_MINI', 'Version': '1.0'})),
            ],
        ),
    ]
