# Generated by Django 4.1.5 on 2025-01-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Configuration', 'verbose_name_plural': 'Configuration'},
        ),
        migrations.RemoveField(
            model_name='config',
            name='data',
        ),
        migrations.AddField(
            model_name='config',
            name='base_url_iccf',
            field=models.URLField(default='https://gamesarchive.iccf.com/archive'),
        ),
        migrations.AddField(
            model_name='config',
            name='base_url_twic',
            field=models.URLField(default='https://theweekinchess.com/zips/twic'),
        ),
        migrations.AddField(
            model_name='config',
            name='folder_import',
            field=models.CharField(default='chess_import', max_length=100),
        ),
        migrations.AddField(
            model_name='config',
            name='iccf_folder',
            field=models.CharField(default='chess/iccf', max_length=100),
        ),
        migrations.AddField(
            model_name='config',
            name='max_missing_twic',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='config',
            name='start_twic_nr',
            field=models.IntegerField(default=1565),
        ),
        migrations.AddField(
            model_name='config',
            name='sub_folder_unzipped',
            field=models.CharField(default='pgn', max_length=50),
        ),
        migrations.AddField(
            model_name='config',
            name='sub_folder_zst',
            field=models.CharField(default='zst', max_length=50),
        ),
        migrations.AddField(
            model_name='config',
            name='twic_folder',
            field=models.CharField(default='chess/twic', max_length=100),
        ),
        migrations.AddField(
            model_name='config',
            name='user_agent',
            field=models.CharField(default='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='volume_download_iccf',
            field=models.CharField(default='VOLUME_DATALAKE_DOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='config',
            name='volume_import',
            field=models.CharField(default='VOLUME_DATALAKE_FRITZ', max_length=50),
        ),
        migrations.AddField(
            model_name='config',
            name='volume_twic',
            field=models.CharField(default='VOLUME_DATALAKE_MINI', max_length=50),
        ),
    ]
