# Generated by Django 4.1.5 on 2025-01-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfmapp', '0002_alter_config_options_remove_config_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichessConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('chunk_size', models.IntegerField(default=104857600)),
                ('download_folder', models.CharField(default='lichess_downloads', max_length=255)),
                ('unzip_volume', models.CharField(default='lichess_unzip_volume', max_length=255)),
                ('unzip_folder', models.CharField(default='lichess_unzipped', max_length=255)),
                ('align_prefix', models.CharField(default='aligned_', max_length=8)),
            ],
            options={
                'verbose_name': 'Lichess Configuration',
                'verbose_name_plural': 'Lichess Configuration',
            },
        ),
    ]
