# Generated by Django 4.1.5 on 2025-01-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfmapp', '0003_lichessconfigmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichessconfigmodel',
            name='align_prefix',
        ),
        migrations.AddField(
            model_name='lichessconfigmodel',
            name='aligned_folder',
            field=models.CharField(default='lichess_aligned_volume', max_length=255),
        ),
        migrations.AddField(
            model_name='lichessconfigmodel',
            name='aligned_volume',
            field=models.CharField(default='lichess_aligned_volume', max_length=255),
        ),
        migrations.AddField(
            model_name='lichessconfigmodel',
            name='download_volume',
            field=models.CharField(default='xxx', max_length=255),
        ),
    ]
