# Generated by Django 4.1.5 on 2025-01-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfmapp', '0004_remove_lichessconfigmodel_align_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichessconfigmodel',
            name='align_prefix',
            field=models.CharField(default='x', max_length=1),
        ),
    ]
