# Generated by Django 4.1.5 on 2025-01-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfmapp', '0005_lichessconfigmodel_align_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichessconfigmodel',
            name='align_prefix',
        ),
    ]
