# Generated by Django 4.1.5 on 2025-01-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfmapp', '0006_remove_lichessconfigmodel_align_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichessconfigmodel',
            name='json_filename_pattern',
            field=models.CharField(default='lichess_eval_', max_length=32),
        ),
        migrations.AddField(
            model_name='lichessconfigmodel',
            name='json_per_file',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='lichessconfigmodel',
            name='unzip_script_path',
            field=models.CharField(default='/opt/airflow/dags/scripts/unzst.sh', max_length=255),
        ),
        migrations.AddField(
            model_name='lichessconfigmodel',
            name='zst_filename_pattern',
            field=models.CharField(default='lichess*eval.jsonl.zst', max_length=32),
        ),
    ]
